// SPDX-License-Identifier: LGPL-3.0-only
#ifndef IP2UNIX_ERRNO_LIST_HH
#define IP2UNIX_ERRNO_LIST_HH

/* Corresponding implementations will be generated by generrno.py. */
std::optional<int> name2errno(const std::string&);
const std::string errno2name(int);

#endif
